{ config, pkgs, lib, ... }:

{
  programs.emacs = {
    enable = true;
    package = pkgs.emacs-gtk;
    extraPackages = epkgs: with epkgs; [
      aggressive-indent
      all-the-icons
      all-the-icons-completion
      add-node-modules-path
      js2-mode
      prettier-js
      rjsx-mode
      typescript-mode
      web-mode
      csv-mode
      dockerfile-mode
      markdown-mode
      nginx-mode
      systemd
      terraform-mode
      toml-mode
      yaml-mode
      treesit-grammars.with-all-grammars
      avy
      dashboard
      diff-hl
      evil-anzu
      evil-goggles
      helpful
      highlight-indent-guides
      multiple-cursors
      rainbow-mode
      dap-mode
      ein
      poetry
      ob-restclient
      org-bullets
      org-download
      cape
      cider
      clj-refactor
      clojure-mode
      clojure-snippets
      consult-lsp
      consult-project-extra
      corfu
      coverage
      eat
      embark
      embark-consult
      evil
      evil-collection
      evil-commentary
      evil-matchit
      evil-surround
      expand-region
      feature-mode
      flycheck
      flycheck-clj-kondo
      htmlize
      json-mode
      ligature
      magit
      magit-section
      marginalia
      mixed-pitch
      modus-themes
      move-text
      mu4e-alert
      nix-mode
      olivetti
      orderless
      org-superstar
      org-msg
      org-mime
      org-roam
      org-roam-ui
      paredit
      pkgs.emacsPackagesCustom.mu4e-dashboard
      pkgs.emacsPackagesCustom.emacs-claude-code
      py-isort
      pytest
      python-black
      pyvenv
      rainbow-delimiters
      restclient
      smartparens
      transient
      treemacs
      treemacs-all-the-icons
      undo-tree
      vertico
      wgrep
      which-key
      origami
      yafolding
      yasnippet
      yasnippet-capf
      yasnippet-snippets
    ];
  };
}
